//// This file is machine-generated by scripts/generate_bezier_bbox_fixtures.py.
//// Oracle bboxes are computed by direct Bernstein evaluation over 200000 samples.

import svg_path/bezier

pub type BezierBBoxFixture {
  BezierBBoxFixture(
    name: String,
    curve: bezier.BezierData,
    min: bezier.Point,
    max: bezier.Point,
  )
}

pub fn fixtures() -> List(BezierBBoxFixture) {
  [
    BezierBBoxFixture(
      name: "linear_diagonal",
      curve: bezier.LinearBezierData(
        start: bezier.Point(1.0, 2.0),
        end: bezier.Point(5.0, -3.0),
      ),
      min: bezier.Point(1.0, -3.0),
      max: bezier.Point(5.0, 2.0),
    ),
    BezierBBoxFixture(
      name: "quadratic_symmetric_peak",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(0.0, 0.0),
        control: bezier.Point(10.0, 10.0),
        end: bezier.Point(20.0, 0.0),
      ),
      min: bezier.Point(0.0, 0.0),
      max: bezier.Point(20.0, 5.0),
    ),
    BezierBBoxFixture(
      name: "quadratic_interior_x_extremum",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(0.0, 0.0),
        control: bezier.Point(10.0, 2.0),
        end: bezier.Point(0.0, 4.0),
      ),
      min: bezier.Point(0.0, 0.0),
      max: bezier.Point(5.0, 4.0),
    ),
    BezierBBoxFixture(
      name: "quadratic_mixed_extrema",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-3.0, 5.0),
        control: bezier.Point(12.0, -8.0),
        end: bezier.Point(6.0, 7.0),
      ),
      min: bezier.Point(-3.0, -1.035714),
      max: bezier.Point(7.714286, 7.0),
    ),
    BezierBBoxFixture(
      name: "cubic_arch",
      curve: bezier.CubicBezierData(
        start: bezier.Point(0.0, 0.0),
        control1: bezier.Point(0.0, 30.0),
        control2: bezier.Point(30.0, 30.0),
        end: bezier.Point(30.0, 0.0),
      ),
      min: bezier.Point(0.0, 0.0),
      max: bezier.Point(30.0, 22.5),
    ),
    BezierBBoxFixture(
      name: "cubic_s_curve",
      curve: bezier.CubicBezierData(
        start: bezier.Point(0.0, 0.0),
        control1: bezier.Point(20.0, 40.0),
        control2: bezier.Point(-10.0, -30.0),
        end: bezier.Point(30.0, 10.0),
      ),
      min: bezier.Point(0.0, -2.833495),
      max: bezier.Point(30.0, 12.833495),
    ),
    BezierBBoxFixture(
      name: "cubic_loopish",
      curve: bezier.CubicBezierData(
        start: bezier.Point(5.0, 1.0),
        control1: bezier.Point(40.0, 20.0),
        control2: bezier.Point(-30.0, 25.0),
        end: bezier.Point(10.0, -15.0),
      ),
      min: bezier.Point(-2.766373, -15.0),
      max: bezier.Point(15.151446, 15.320527),
    ),
    BezierBBoxFixture(
      name: "generated_linear_001",
      curve: bezier.LinearBezierData(
        start: bezier.Point(13.902, -26.073),
        end: bezier.Point(22.511, 3.074),
      ),
      min: bezier.Point(13.902, -26.073),
      max: bezier.Point(22.511, 3.074),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_001",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-9.881, -8.999),
        control: bezier.Point(41.606, -35.489),
        end: bezier.Point(1.635, -41.056),
      ),
      min: bezier.Point(-9.881, -41.056),
      max: bezier.Point(19.104011, -8.999),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_001",
      curve: bezier.CubicBezierData(
        start: bezier.Point(1.781, 44.346),
        control1: bezier.Point(32.548, -3.012),
        control2: bezier.Point(33.131, 24.681),
        end: bezier.Point(33.597, -15.639),
      ),
      min: bezier.Point(1.781, -15.639),
      max: bezier.Point(33.597, 44.346),
    ),
    BezierBBoxFixture(
      name: "generated_linear_002",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-19.667, 6.308),
        end: bezier.Point(-10.455, -41.28),
      ),
      min: bezier.Point(-19.667, -41.28),
      max: bezier.Point(-10.455, 6.308),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_002",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(17.229, -34.944),
        control: bezier.Point(-22.683, 48.946),
        end: bezier.Point(-47.651, -19.81),
      ),
      min: bezier.Point(-47.651, -34.944),
      max: bezier.Point(17.229, 11.159613),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_002",
      curve: bezier.CubicBezierData(
        start: bezier.Point(37.489, -18.376),
        control1: bezier.Point(11.484, 31.46),
        control2: bezier.Point(20.196, 7.446),
        end: bezier.Point(-3.508, -44.881),
      ),
      min: bezier.Point(-3.508, -44.881),
      max: bezier.Point(37.489, 8.945008),
    ),
    BezierBBoxFixture(
      name: "generated_linear_003",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-5.929, -23.771),
        end: bezier.Point(44.881, 0.259),
      ),
      min: bezier.Point(-5.929, -23.771),
      max: bezier.Point(44.881, 0.259),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_003",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-27.537, -27.63),
        control: bezier.Point(35.124, -45.246),
        end: bezier.Point(-15.156, 41.127),
      ),
      min: bezier.Point(-27.537, -30.614195),
      max: bezier.Point(7.228062, 41.127),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_003",
      curve: bezier.CubicBezierData(
        start: bezier.Point(18.034, -15.988),
        control1: bezier.Point(23.696, 48.264),
        control2: bezier.Point(11.83, 28.003),
        end: bezier.Point(46.037, -42.899),
      ),
      min: bezier.Point(18.034, -42.899),
      max: bezier.Point(46.037, 22.76097),
    ),
    BezierBBoxFixture(
      name: "generated_linear_004",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-42.083, -38.856),
        end: bezier.Point(33.777, 48.659),
      ),
      min: bezier.Point(-42.083, -38.856),
      max: bezier.Point(33.777, 48.659),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_004",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-12.229, 37.966),
        control: bezier.Point(-36.77, -15.015),
        end: bezier.Point(-7.856, 13.539),
      ),
      min: bezier.Point(-23.495686, 3.539234),
      max: bezier.Point(-7.856, 37.966),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_004",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-39.711, 18.094),
        control1: bezier.Point(18.116, -17.726),
        control2: bezier.Point(31.979, -24.604),
        end: bezier.Point(-7.691, -42.405),
      ),
      min: bezier.Point(-39.711, -42.405),
      max: bezier.Point(14.869396, 18.094),
    ),
    BezierBBoxFixture(
      name: "generated_linear_005",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-25.438, 23.246),
        end: bezier.Point(-8.556, -34.511),
      ),
      min: bezier.Point(-25.438, -34.511),
      max: bezier.Point(-8.556, 23.246),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_005",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(7.887, -32.575),
        control: bezier.Point(37.41, 47.678),
        end: bezier.Point(43.067, -23.545),
      ),
      min: bezier.Point(7.887, -32.575),
      max: bezier.Point(43.067, 9.943577),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_005",
      curve: bezier.CubicBezierData(
        start: bezier.Point(20.532, -27.827),
        control1: bezier.Point(-39.662, 12.817),
        control2: bezier.Point(-37.388, -40.605),
        end: bezier.Point(-9.348, 21.316),
      ),
      min: bezier.Point(-28.323965, -27.827),
      max: bezier.Point(20.532, 21.316),
    ),
    BezierBBoxFixture(
      name: "generated_linear_006",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-9.755, 39.281),
        end: bezier.Point(20.735, 1.692),
      ),
      min: bezier.Point(-9.755, 1.692),
      max: bezier.Point(20.735, 39.281),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_006",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-47.82, -0.857),
        control: bezier.Point(-3.932, -47.488),
        end: bezier.Point(12.65, 34.428),
      ),
      min: bezier.Point(-47.82, -17.772604),
      max: bezier.Point(12.65, 34.428),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_006",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-40.639, 46.18),
        control1: bezier.Point(41.012, -8.934),
        control2: bezier.Point(-28.815, 7.67),
        end: bezier.Point(28.414, -47.318),
      ),
      min: bezier.Point(-40.639, -47.318),
      max: bezier.Point(28.414, 46.18),
    ),
    BezierBBoxFixture(
      name: "generated_linear_007",
      curve: bezier.LinearBezierData(
        start: bezier.Point(45.804, -33.412),
        end: bezier.Point(25.826, 6.117),
      ),
      min: bezier.Point(25.826, -33.412),
      max: bezier.Point(45.804, 6.117),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_007",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(27.93, 8.194),
        control: bezier.Point(35.971, 16.204),
        end: bezier.Point(-1.19, 21.713),
      ),
      min: bezier.Point(-1.19, 8.194),
      max: bezier.Point(29.360416, 21.713),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_007",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-45.508, 45.561),
        control1: bezier.Point(-49.091, -15.734),
        control2: bezier.Point(-18.926, -0.108),
        end: bezier.Point(-28.74, -4.529),
      ),
      min: bezier.Point(-45.80542, -4.529),
      max: bezier.Point(-26.766472, 45.561),
    ),
    BezierBBoxFixture(
      name: "generated_linear_008",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-22.93, -4.838),
        end: bezier.Point(-20.834, -11.159),
      ),
      min: bezier.Point(-22.93, -11.159),
      max: bezier.Point(-20.834, -4.838),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_008",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-35.855, 17.794),
        control: bezier.Point(24.669, -0.311),
        end: bezier.Point(20.783, -42.174),
      ),
      min: bezier.Point(-35.855, -42.174),
      max: bezier.Point(21.017451, 17.794),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_008",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-11.099, -14.218),
        control1: bezier.Point(21.965, 2.363),
        control2: bezier.Point(-25.698, -16.084),
        end: bezier.Point(-10.643, -44.471),
      ),
      min: bezier.Point(-13.673543, -44.471),
      max: bezier.Point(0.851364, -7.947449),
    ),
    BezierBBoxFixture(
      name: "generated_linear_009",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-22.031, -28.986),
        end: bezier.Point(-41.348, -44.032),
      ),
      min: bezier.Point(-41.348, -44.032),
      max: bezier.Point(-22.031, -28.986),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_009",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(33.823, 23.504),
        control: bezier.Point(-46.806, -6.666),
        end: bezier.Point(44.155, 47.566),
      ),
      min: bezier.Point(-4.064031, 12.719553),
      max: bezier.Point(44.155, 47.566),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_009",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-31.862, 1.502),
        control1: bezier.Point(-18.999, -35.332),
        control2: bezier.Point(4.278, -33.361),
        end: bezier.Point(5.66, 2.228),
      ),
      min: bezier.Point(-31.862, -25.303037),
      max: bezier.Point(5.66, 2.228),
    ),
    BezierBBoxFixture(
      name: "generated_linear_010",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-12.674, 5.692),
        end: bezier.Point(-19.717, 49.937),
      ),
      min: bezier.Point(-19.717, 5.692),
      max: bezier.Point(-12.674, 49.937),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_010",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-17.145, 3.437),
        control: bezier.Point(42.631, -12.508),
        end: bezier.Point(-15.669, 9.105),
      ),
      min: bezier.Point(-17.145, -3.332344),
      max: bezier.Point(13.116613, 9.105),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_010",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-38.693, -19.224),
        control1: bezier.Point(-45.353, 35.701),
        control2: bezier.Point(7.395, 43.23),
        end: bezier.Point(-39.43, -38.5),
      ),
      min: bezier.Point(-39.43, -38.5),
      max: bezier.Point(-19.851417, 22.478712),
    ),
    BezierBBoxFixture(
      name: "generated_linear_011",
      curve: bezier.LinearBezierData(
        start: bezier.Point(11.02, -38.578),
        end: bezier.Point(30.942, -27.484),
      ),
      min: bezier.Point(11.02, -38.578),
      max: bezier.Point(30.942, -27.484),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_011",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(47.831, -6.904),
        control: bezier.Point(24.931, 7.45),
        end: bezier.Point(47.392, 12.105),
      ),
      min: bezier.Point(36.270188, -6.904),
      max: bezier.Point(47.831, 12.105),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_011",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-35.465, -31.683),
        control1: bezier.Point(27.942, 6.929),
        control2: bezier.Point(-1.109, -44.967),
        end: bezier.Point(16.117, -21.609),
      ),
      min: bezier.Point(-35.465, -31.683),
      max: bezier.Point(16.117, -16.8829),
    ),
    BezierBBoxFixture(
      name: "generated_linear_012",
      curve: bezier.LinearBezierData(
        start: bezier.Point(21.181, -48.634),
        end: bezier.Point(19.355, -29.965),
      ),
      min: bezier.Point(19.355, -48.634),
      max: bezier.Point(21.181, -29.965),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_012",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-10.259, -40.506),
        control: bezier.Point(-42.84, 27.666),
        end: bezier.Point(49.268, 0.12),
      ),
      min: bezier.Point(-18.772354, -40.506),
      max: bezier.Point(49.268, 8.047267),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_012",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-14.172, -26.023),
        control1: bezier.Point(46.567, 4.624),
        control2: bezier.Point(-45.889, -14.814),
        end: bezier.Point(10.689, 16.358),
      ),
      min: bezier.Point(-14.172, -26.023),
      max: bezier.Point(10.689, 16.358),
    ),
    BezierBBoxFixture(
      name: "generated_linear_013",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-47.626, 35.479),
        end: bezier.Point(16.409, 27.118),
      ),
      min: bezier.Point(-47.626, 27.118),
      max: bezier.Point(16.409, 35.479),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_013",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-11.526, 0.103),
        control: bezier.Point(4.381, -20.367),
        end: bezier.Point(31.569, 4.173),
      ),
      min: bezier.Point(-11.526, -9.206507),
      max: bezier.Point(31.569, 4.173),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_013",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-37.829, -37.667),
        control1: bezier.Point(35.944, -25.246),
        control2: bezier.Point(-44.919, -8.828),
        end: bezier.Point(42.84, 37.743),
      ),
      min: bezier.Point(-37.829, -37.667),
      max: bezier.Point(42.84, 37.743),
    ),
    BezierBBoxFixture(
      name: "generated_linear_014",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-40.827, -32.598),
        end: bezier.Point(-30.439, 25.448),
      ),
      min: bezier.Point(-40.827, -32.598),
      max: bezier.Point(-30.439, 25.448),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_014",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-40.735, 3.398),
        control: bezier.Point(23.691, 28.729),
        end: bezier.Point(-5.319, -27.298),
      ),
      min: bezier.Point(-40.735, -27.298),
      max: bezier.Point(3.688022, 11.284865),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_014",
      curve: bezier.CubicBezierData(
        start: bezier.Point(23.849, -24.804),
        control1: bezier.Point(45.165, -15.149),
        control2: bezier.Point(44.176, -30.368),
        end: bezier.Point(19.287, -26.182),
      ),
      min: bezier.Point(19.287, -26.928661),
      max: bezier.Point(38.957439, -21.534754),
    ),
    BezierBBoxFixture(
      name: "generated_linear_015",
      curve: bezier.LinearBezierData(
        start: bezier.Point(29.129, -0.313),
        end: bezier.Point(-44.404, 41.324),
      ),
      min: bezier.Point(-44.404, -0.313),
      max: bezier.Point(29.129, 41.324),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_015",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(14.987, -42.831),
        control: bezier.Point(-47.579, -30.734),
        end: bezier.Point(22.316, 47.929),
      ),
      min: bezier.Point(-14.565127, -42.831),
      max: bezier.Point(22.316, 47.929),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_015",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-4.326, 3.177),
        control1: bezier.Point(25.927, 27.592),
        control2: bezier.Point(-37.388, -41.196),
        end: bezier.Point(46.544, 44.536),
      ),
      min: bezier.Point(-4.326, -0.069621),
      max: bezier.Point(46.544, 44.536),
    ),
    BezierBBoxFixture(
      name: "generated_linear_016",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-24.759, 3.982),
        end: bezier.Point(-40.271, -40.737),
      ),
      min: bezier.Point(-40.271, -40.737),
      max: bezier.Point(-24.759, 3.982),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_016",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(32.32, -12.357),
        control: bezier.Point(-40.476, -46.069),
        end: bezier.Point(-4.678, -24.366),
      ),
      min: bezier.Point(-16.478807, -32.865868),
      max: bezier.Point(32.32, -12.357),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_016",
      curve: bezier.CubicBezierData(
        start: bezier.Point(38.805, 23.345),
        control1: bezier.Point(-31.91, -12.319),
        control2: bezier.Point(15.483, 13.355),
        end: bezier.Point(41.318, -40.983),
      ),
      min: bezier.Point(1.675958, -40.983),
      max: bezier.Point(41.318, 23.345),
    ),
    BezierBBoxFixture(
      name: "generated_linear_017",
      curve: bezier.LinearBezierData(
        start: bezier.Point(48.277, 46.83),
        end: bezier.Point(-45.362, -37.268),
      ),
      min: bezier.Point(-45.362, -37.268),
      max: bezier.Point(48.277, 46.83),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_017",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-11.731, -1.518),
        control: bezier.Point(-3.763, 38.698),
        end: bezier.Point(11.161, -1.701),
      ),
      min: bezier.Point(-11.731, -1.701),
      max: bezier.Point(11.161, 18.544354),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_017",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-29.556, 3.181),
        control1: bezier.Point(34.295, -36.511),
        control2: bezier.Point(-45.655, 17.969),
        end: bezier.Point(-7.527, 21.173),
      ),
      min: bezier.Point(-29.556, -11.241187),
      max: bezier.Point(-3.83053, 21.173),
    ),
    BezierBBoxFixture(
      name: "generated_linear_018",
      curve: bezier.LinearBezierData(
        start: bezier.Point(24.332, 20.952),
        end: bezier.Point(13.882, 21.755),
      ),
      min: bezier.Point(13.882, 20.952),
      max: bezier.Point(24.332, 21.755),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_018",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(31.639, -28.575),
        control: bezier.Point(-32.044, 37.572),
        end: bezier.Point(-21.175, -20.64),
      ),
      min: bezier.Point(-22.759601, -28.575),
      max: bezier.Point(31.639, 6.608828),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_018",
      curve: bezier.CubicBezierData(
        start: bezier.Point(11.486, -45.925),
        control1: bezier.Point(30.251, 44.594),
        control2: bezier.Point(42.944, 43.899),
        end: bezier.Point(3.659, -25.67),
      ),
      min: bezier.Point(3.659, -45.925),
      max: bezier.Point(29.379077, 24.460194),
    ),
    BezierBBoxFixture(
      name: "generated_linear_019",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-40.098, 14.027),
        end: bezier.Point(-31.408, 2.557),
      ),
      min: bezier.Point(-40.098, 2.557),
      max: bezier.Point(-31.408, 14.027),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_019",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-22.659, 27.255),
        control: bezier.Point(34.346, -39.383),
        end: bezier.Point(43.906, -26.509),
      ),
      min: bezier.Point(-22.659, -28.593464),
      max: bezier.Point(43.906, 27.255),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_019",
      curve: bezier.CubicBezierData(
        start: bezier.Point(12.929, -45.732),
        control1: bezier.Point(23.08, -37.912),
        control2: bezier.Point(32.891, 10.738),
        end: bezier.Point(-22.144, -11.138),
      ),
      min: bezier.Point(-22.144, -45.732),
      max: bezier.Point(20.824259, -5.530526),
    ),
    BezierBBoxFixture(
      name: "generated_linear_020",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-15.724, -10.737),
        end: bezier.Point(43.266, -46.152),
      ),
      min: bezier.Point(-15.724, -46.152),
      max: bezier.Point(43.266, -10.737),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_020",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-46.128, 0.895),
        control: bezier.Point(-43.673, -38.599),
        end: bezier.Point(5.603, -23.693),
      ),
      min: bezier.Point(-46.128, -27.777354),
      max: bezier.Point(5.603, 0.895),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_020",
      curve: bezier.CubicBezierData(
        start: bezier.Point(40.327, 0.754),
        control1: bezier.Point(20.045, 5.429),
        control2: bezier.Point(-41.614, 20.612),
        end: bezier.Point(-26.062, -30.201),
      ),
      min: bezier.Point(-28.549241, -30.201),
      max: bezier.Point(40.327, 6.537307),
    ),
    BezierBBoxFixture(
      name: "generated_linear_021",
      curve: bezier.LinearBezierData(
        start: bezier.Point(7.07, -9.675),
        end: bezier.Point(-14.268, -14.157),
      ),
      min: bezier.Point(-14.268, -14.157),
      max: bezier.Point(7.07, -9.675),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_021",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-35.239, -21.611),
        control: bezier.Point(-25.764, -2.368),
        end: bezier.Point(-12.326, 40.536),
      ),
      min: bezier.Point(-35.239, -21.611),
      max: bezier.Point(-12.326, 40.536),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_021",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-32.481, -30.508),
        control1: bezier.Point(21.39, -1.593),
        control2: bezier.Point(40.87, 45.793),
        end: bezier.Point(32.332, 33.404),
      ),
      min: bezier.Point(-32.481, -30.508),
      max: bezier.Point(34.261379, 35.427187),
    ),
    BezierBBoxFixture(
      name: "generated_linear_022",
      curve: bezier.LinearBezierData(
        start: bezier.Point(22.514, 41.333),
        end: bezier.Point(-35.26, -15.424),
      ),
      min: bezier.Point(-35.26, -15.424),
      max: bezier.Point(22.514, 41.333),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_022",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(24.261, 0.008),
        control: bezier.Point(39.496, 0.065),
        end: bezier.Point(12.369, 26.658),
      ),
      min: bezier.Point(12.369, 0.008),
      max: bezier.Point(29.74009, 26.658),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_022",
      curve: bezier.CubicBezierData(
        start: bezier.Point(23.429, 7.061),
        control1: bezier.Point(-33.157, -27.631),
        control2: bezier.Point(35.588, -37.732),
        end: bezier.Point(23.97, 41.59),
      ),
      min: bezier.Point(0.787114, -18.930868),
      max: bezier.Point(25.320734, 41.59),
    ),
    BezierBBoxFixture(
      name: "generated_linear_023",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-43.815, 3.226),
        end: bezier.Point(-10.812, 40.568),
      ),
      min: bezier.Point(-43.815, 3.226),
      max: bezier.Point(-10.812, 40.568),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_023",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-23.992, 14.674),
        control: bezier.Point(-9.955, 17.808),
        end: bezier.Point(-44.983, -27.452),
      ),
      min: bezier.Point(-44.983, -27.452),
      max: bezier.Point(-19.976156, 14.876958),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_023",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-10.637, 16.087),
        control1: bezier.Point(-45.194, 15.701),
        control2: bezier.Point(49.284, 9.28),
        end: bezier.Point(-37.185, -43.554),
      ),
      min: bezier.Point(-37.185, -43.554),
      max: bezier.Point(0.449908, 16.087),
    ),
    BezierBBoxFixture(
      name: "generated_linear_024",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-47.029, -13.562),
        end: bezier.Point(14.996, -48.574),
      ),
      min: bezier.Point(-47.029, -48.574),
      max: bezier.Point(14.996, -13.562),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_024",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(45.998, 19.683),
        control: bezier.Point(34.386, 27.538),
        end: bezier.Point(42.003, -12.44),
      ),
      min: bezier.Point(38.985751, -12.44),
      max: bezier.Point(45.998, 20.972926),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_024",
      curve: bezier.CubicBezierData(
        start: bezier.Point(40.33, 17.306),
        control1: bezier.Point(-22.885, -19.372),
        control2: bezier.Point(42.984, -2.57),
        end: bezier.Point(46.435, -15.466),
      ),
      min: bezier.Point(13.022574, -15.466),
      max: bezier.Point(46.435, 17.306),
    ),
    BezierBBoxFixture(
      name: "generated_linear_025",
      curve: bezier.LinearBezierData(
        start: bezier.Point(8.501, 0.752),
        end: bezier.Point(-7.433, -32.941),
      ),
      min: bezier.Point(-7.433, -32.941),
      max: bezier.Point(8.501, 0.752),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_025",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(33.958, 46.024),
        control: bezier.Point(40.22, 0.624),
        end: bezier.Point(-21.955, 0.193),
      ),
      min: bezier.Point(-21.955, 0.193),
      max: bezier.Point(34.530974, 46.024),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_025",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-23.268, -28.324),
        control1: bezier.Point(-24.408, -49.656),
        control2: bezier.Point(43.215, 8.243),
        end: bezier.Point(43.33, -23.422),
      ),
      min: bezier.Point(-23.282253, -33.171093),
      max: bezier.Point(43.33, -13.72785),
    ),
    BezierBBoxFixture(
      name: "generated_linear_026",
      curve: bezier.LinearBezierData(
        start: bezier.Point(38.944, 29.822),
        end: bezier.Point(18.61, -45.682),
      ),
      min: bezier.Point(18.61, -45.682),
      max: bezier.Point(38.944, 29.822),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_026",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-31.478, -2.638),
        control: bezier.Point(17.894, -36.476),
        end: bezier.Point(-40.527, -48.069),
      ),
      min: bezier.Point(-40.527, -48.069),
      max: bezier.Point(-8.864339, -2.638),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_026",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-18.425, 49.27),
        control1: bezier.Point(-16.249, 35.774),
        control2: bezier.Point(-14.619, -5.967),
        end: bezier.Point(-16.123, -49.171),
      ),
      min: bezier.Point(-18.425, -49.171),
      max: bezier.Point(-15.539226, 49.27),
    ),
    BezierBBoxFixture(
      name: "generated_linear_027",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-23.544, 12.395),
        end: bezier.Point(-45.488, -21.02),
      ),
      min: bezier.Point(-45.488, -21.02),
      max: bezier.Point(-23.544, 12.395),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_027",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-38.021, -44.126),
        control: bezier.Point(-4.157, -12.507),
        end: bezier.Point(14.548, -5.728),
      ),
      min: bezier.Point(-38.021, -44.126),
      max: bezier.Point(14.548, -5.728),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_027",
      curve: bezier.CubicBezierData(
        start: bezier.Point(2.924, -22.125),
        control1: bezier.Point(-46.469, 44.415),
        control2: bezier.Point(-24.665, -37.482),
        end: bezier.Point(40.311, 34.588),
      ),
      min: bezier.Point(-24.084822, -22.125),
      max: bezier.Point(40.311, 34.588),
    ),
    BezierBBoxFixture(
      name: "generated_linear_028",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-3.317, 12.882),
        end: bezier.Point(-22.522, -23.494),
      ),
      min: bezier.Point(-22.522, -23.494),
      max: bezier.Point(-3.317, 12.882),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_028",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(48.23, 28.31),
        control: bezier.Point(30.074, 39.266),
        end: bezier.Point(21.919, 31.918),
      ),
      min: bezier.Point(21.919, 28.31),
      max: bezier.Point(48.23, 34.867798),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_028",
      curve: bezier.CubicBezierData(
        start: bezier.Point(6.519, 25.133),
        control1: bezier.Point(17.434, -40.726),
        control2: bezier.Point(-39.063, -18.306),
        end: bezier.Point(6.794, -32.935),
      ),
      min: bezier.Point(-11.426513, -32.935),
      max: bezier.Point(7.952048, 25.133),
    ),
    BezierBBoxFixture(
      name: "generated_linear_029",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-27.856, 48.108),
        end: bezier.Point(12.013, 35.335),
      ),
      min: bezier.Point(-27.856, 35.335),
      max: bezier.Point(12.013, 48.108),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_029",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(23.235, -17.305),
        control: bezier.Point(-45.912, -11.661),
        end: bezier.Point(18.286, -49.455),
      ),
      min: bezier.Point(-12.62167, -49.455),
      max: bezier.Point(23.235, -16.571662),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_029",
      curve: bezier.CubicBezierData(
        start: bezier.Point(5.371, 42.23),
        control1: bezier.Point(-33.834, -49.494),
        control2: bezier.Point(-13.737, 36.917),
        end: bezier.Point(-34.279, -40.719),
      ),
      min: bezier.Point(-34.279, -40.719),
      max: bezier.Point(5.371, 42.23),
    ),
    BezierBBoxFixture(
      name: "generated_linear_030",
      curve: bezier.LinearBezierData(
        start: bezier.Point(39.441, -34.9),
        end: bezier.Point(-47.548, 26.156),
      ),
      min: bezier.Point(-47.548, -34.9),
      max: bezier.Point(39.441, 26.156),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_030",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(6.599, -23.987),
        control: bezier.Point(-8.319, -8.024),
        end: bezier.Point(-13.236, 44.581),
      ),
      min: bezier.Point(-13.236, -23.987),
      max: bezier.Point(6.599, 44.581),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_030",
      curve: bezier.CubicBezierData(
        start: bezier.Point(48.118, 46.008),
        control1: bezier.Point(-46.033, -42.791),
        control2: bezier.Point(-26.79, -13.049),
        end: bezier.Point(49.058, -17.234),
      ),
      min: bezier.Point(-15.384807, -18.799584),
      max: bezier.Point(49.058, 46.008),
    ),
    BezierBBoxFixture(
      name: "generated_linear_031",
      curve: bezier.LinearBezierData(
        start: bezier.Point(23.851, 29.4),
        end: bezier.Point(46.324, -42.648),
      ),
      min: bezier.Point(23.851, -42.648),
      max: bezier.Point(46.324, 29.4),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_031",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(4.722, -36.059),
        control: bezier.Point(-2.87, 36.583),
        end: bezier.Point(21.573, -43.729),
      ),
      min: bezier.Point(2.922766, -43.729),
      max: bezier.Point(21.573, -1.559345),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_031",
      curve: bezier.CubicBezierData(
        start: bezier.Point(32.715, -17.799),
        control1: bezier.Point(36.521, -44.674),
        control2: bezier.Point(-0.446, -41.542),
        end: bezier.Point(20.183, 49.218),
      ),
      min: bezier.Point(13.883318, -32.540887),
      max: bezier.Point(32.992412, 49.218),
    ),
    BezierBBoxFixture(
      name: "generated_linear_032",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-29.189, -17.485),
        end: bezier.Point(-23.377, -19.9),
      ),
      min: bezier.Point(-29.189, -19.9),
      max: bezier.Point(-23.377, -17.485),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_032",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-38.222, 14.998),
        control: bezier.Point(42.643, -42.833),
        end: bezier.Point(0.463, -36.501),
      ),
      min: bezier.Point(-38.222, -37.125881),
      max: bezier.Point(14.922364, 14.998),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_032",
      curve: bezier.CubicBezierData(
        start: bezier.Point(43.447, 32.578),
        control1: bezier.Point(47.544, -33.5),
        control2: bezier.Point(22.431, 9.615),
        end: bezier.Point(32.44, -44.581),
      ),
      min: bezier.Point(30.064258, -44.581),
      max: bezier.Point(43.903231, 32.578),
    ),
    BezierBBoxFixture(
      name: "generated_linear_033",
      curve: bezier.LinearBezierData(
        start: bezier.Point(48.112, -35.009),
        end: bezier.Point(-13.56, -12.056),
      ),
      min: bezier.Point(-13.56, -35.009),
      max: bezier.Point(48.112, -12.056),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_033",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-23.337, 12.499),
        control: bezier.Point(-2.214, 8.699),
        end: bezier.Point(-39.188, -11.401),
      ),
      min: bezier.Point(-39.188, -11.401),
      max: bezier.Point(-15.657066, 12.499),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_033",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-27.338, -23.07),
        control1: bezier.Point(-41.659, 11.365),
        control2: bezier.Point(25.634, -14.41),
        end: bezier.Point(-24.033, -17.144),
      ),
      min: bezier.Point(-29.384457, -23.07),
      max: bezier.Point(-5.461776, -5.316023),
    ),
    BezierBBoxFixture(
      name: "generated_linear_034",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-20.031, 1.35),
        end: bezier.Point(-1.204, 28.656),
      ),
      min: bezier.Point(-20.031, 1.35),
      max: bezier.Point(-1.204, 28.656),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_034",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-45.136, 36.158),
        control: bezier.Point(-48.061, 11.6),
        end: bezier.Point(-21.072, 38.657),
      ),
      min: bezier.Point(-45.422007, 24.473502),
      max: bezier.Point(-21.072, 38.657),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_034",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-37.151, 17.67),
        control1: bezier.Point(19.744, 6.902),
        control2: bezier.Point(28.748, 29.581),
        end: bezier.Point(24.567, -48.955),
      ),
      min: bezier.Point(-37.151, -48.955),
      max: bezier.Point(25.454031, 17.67),
    ),
    BezierBBoxFixture(
      name: "generated_linear_035",
      curve: bezier.LinearBezierData(
        start: bezier.Point(13.671, 29.796),
        end: bezier.Point(-35.807, 41.927),
      ),
      min: bezier.Point(-35.807, 29.796),
      max: bezier.Point(13.671, 41.927),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_035",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-19.633, 5.663),
        control: bezier.Point(41.707, 33.203),
        end: bezier.Point(41.863, -43.011),
      ),
      min: bezier.Point(-19.633, -43.011),
      max: bezier.Point(41.863, 12.973095),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_035",
      curve: bezier.CubicBezierData(
        start: bezier.Point(14.83, -35.952),
        control1: bezier.Point(-44.68, -15.241),
        control2: bezier.Point(10.081, 45.285),
        end: bezier.Point(39.768, 2.878),
      ),
      min: bezier.Point(-11.766104, -35.952),
      max: bezier.Point(39.768, 17.613961),
    ),
    BezierBBoxFixture(
      name: "generated_linear_036",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-9.622, 9.889),
        end: bezier.Point(-6.838, 12.286),
      ),
      min: bezier.Point(-9.622, 9.889),
      max: bezier.Point(-6.838, 12.286),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_036",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(6.255, -27.62),
        control: bezier.Point(22.28, -9.384),
        end: bezier.Point(-34.387, 30.059),
      ),
      min: bezier.Point(-34.387, -27.62),
      max: bezier.Point(9.787722, 30.059),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_036",
      curve: bezier.CubicBezierData(
        start: bezier.Point(44.34, 41.9),
        control1: bezier.Point(41.95, 30.627),
        control2: bezier.Point(19.348, -26.249),
        end: bezier.Point(22.763, 2.236),
      ),
      min: bezier.Point(22.412443, -5.661631),
      max: bezier.Point(44.34, 41.9),
    ),
    BezierBBoxFixture(
      name: "generated_linear_037",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-39.751, 28.147),
        end: bezier.Point(-30.701, 45.731),
      ),
      min: bezier.Point(-39.751, 28.147),
      max: bezier.Point(-30.701, 45.731),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_037",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-46.318, -28.644),
        control: bezier.Point(-15.417, 29.049),
        end: bezier.Point(-39.542, -9.747),
      ),
      min: bezier.Point(-46.318, -28.644),
      max: bezier.Point(-28.964898, 5.851976),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_037",
      curve: bezier.CubicBezierData(
        start: bezier.Point(11.141, -8.04),
        control1: bezier.Point(42.474, -23.743),
        control2: bezier.Point(-0.236, -11.985),
        end: bezier.Point(-26.775, 33.189),
      ),
      min: bezier.Point(-26.775, -14.641488),
      max: bezier.Point(22.167318, 33.189),
    ),
    BezierBBoxFixture(
      name: "generated_linear_038",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-14.06, -27.217),
        end: bezier.Point(25.84, -21.318),
      ),
      min: bezier.Point(-14.06, -27.217),
      max: bezier.Point(25.84, -21.318),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_038",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-47.388, 24.473),
        control: bezier.Point(30.531, -30.616),
        end: bezier.Point(-6.77, -26.422),
      ),
      min: bezier.Point(-47.388, -26.718706),
      max: bezier.Point(5.305721, 24.473),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_038",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-4.631, -5.959),
        control1: bezier.Point(19.146, 30.195),
        control2: bezier.Point(-29.051, 31.606),
        end: bezier.Point(-15.783, -7.24),
      ),
      min: bezier.Point(-18.137954, -7.24),
      max: bezier.Point(2.067587, 21.525521),
    ),
    BezierBBoxFixture(
      name: "generated_linear_039",
      curve: bezier.LinearBezierData(
        start: bezier.Point(42.685, 3.348),
        end: bezier.Point(3.85, 48.011),
      ),
      min: bezier.Point(3.85, 3.348),
      max: bezier.Point(42.685, 48.011),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_039",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(35.09, -17.256),
        control: bezier.Point(-24.83, 30.398),
        end: bezier.Point(25.66, 43.554),
      ),
      min: bezier.Point(2.571148, -17.256),
      max: bezier.Point(35.09, 43.554),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_039",
      curve: bezier.CubicBezierData(
        start: bezier.Point(20.988, 7.481),
        control1: bezier.Point(-39.498, -5.988),
        control2: bezier.Point(-49.916, -2.669),
        end: bezier.Point(30.999, 45.044),
      ),
      min: bezier.Point(-27.031985, 0.612321),
      max: bezier.Point(30.999, 45.044),
    ),
    BezierBBoxFixture(
      name: "generated_linear_040",
      curve: bezier.LinearBezierData(
        start: bezier.Point(46.615, -13.097),
        end: bezier.Point(42.941, 0.252),
      ),
      min: bezier.Point(42.941, -13.097),
      max: bezier.Point(46.615, 0.252),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_040",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(8.226, 38.952),
        control: bezier.Point(16.794, 33.169),
        end: bezier.Point(29.293, 24.31),
      ),
      min: bezier.Point(8.226, 24.31),
      max: bezier.Point(29.293, 38.952),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_040",
      curve: bezier.CubicBezierData(
        start: bezier.Point(28.792, 41.325),
        control1: bezier.Point(11.208, -4.378),
        control2: bezier.Point(-33.881, -39.219),
        end: bezier.Point(-45.65, 23.784),
      ),
      min: bezier.Point(-45.65, -10.443064),
      max: bezier.Point(28.792, 41.325),
    ),
    BezierBBoxFixture(
      name: "generated_linear_041",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-20.818, 36.543),
        end: bezier.Point(19.32, -25.277),
      ),
      min: bezier.Point(-20.818, -25.277),
      max: bezier.Point(19.32, 36.543),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_041",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-39.216, 0.353),
        control: bezier.Point(37.088, 48.006),
        end: bezier.Point(32.332, -0.201),
      ),
      min: bezier.Point(-39.216, -0.201),
      max: bezier.Point(32.611047, 24.0418),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_041",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-40.685, -44.137),
        control1: bezier.Point(-45.914, 18.557),
        control2: bezier.Point(42.32, -17.611),
        end: bezier.Point(45.641, 8.178),
      ),
      min: bezier.Point(-40.908481, -44.137),
      max: bezier.Point(45.641, 8.178),
    ),
    BezierBBoxFixture(
      name: "generated_linear_042",
      curve: bezier.LinearBezierData(
        start: bezier.Point(40.32, -9.014),
        end: bezier.Point(38.96, 27.119),
      ),
      min: bezier.Point(38.96, -9.014),
      max: bezier.Point(40.32, 27.119),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_042",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(45.341, 12.965),
        control: bezier.Point(1.671, -7.331),
        end: bezier.Point(-43.748, 39.056),
      ),
      min: bezier.Point(-43.748, 6.787599),
      max: bezier.Point(45.341, 39.056),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_042",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-21.821, -21.858),
        control1: bezier.Point(-35.178, -42.759),
        control2: bezier.Point(-27.407, -0.172),
        end: bezier.Point(-9.135, 35.17),
      ),
      min: bezier.Point(-28.537679, -27.387703),
      max: bezier.Point(-9.135, 35.17),
    ),
    BezierBBoxFixture(
      name: "generated_linear_043",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-20.349, 35.55),
        end: bezier.Point(-34.704, -3.365),
      ),
      min: bezier.Point(-34.704, -3.365),
      max: bezier.Point(-20.349, 35.55),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_043",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-37.498, -45.805),
        control: bezier.Point(-0.781, -6.605),
        end: bezier.Point(9.595, -34.739),
      ),
      min: bezier.Point(-37.498, -45.805),
      max: bezier.Point(9.595, -22.98384),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_043",
      curve: bezier.CubicBezierData(
        start: bezier.Point(21.404, 23.535),
        control1: bezier.Point(49.443, 27.029),
        control2: bezier.Point(-16.756, 47.061),
        end: bezier.Point(21.79, 32.896),
      ),
      min: bezier.Point(9.385117, 23.535),
      max: bezier.Point(28.549649, 37.902521),
    ),
    BezierBBoxFixture(
      name: "generated_linear_044",
      curve: bezier.LinearBezierData(
        start: bezier.Point(12.183, -16.878),
        end: bezier.Point(30.244, -8.729),
      ),
      min: bezier.Point(12.183, -16.878),
      max: bezier.Point(30.244, -8.729),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_044",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-49.303, 26.482),
        control: bezier.Point(-36.358, 29.148),
        end: bezier.Point(-30.041, 28.158),
      ),
      min: bezier.Point(-49.303, 26.482),
      max: bezier.Point(-30.041, 28.42608),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_044",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-22.537, 1.662),
        control1: bezier.Point(-36.98, 41.01),
        control2: bezier.Point(43.952, 42.106),
        end: bezier.Point(-7.275, 41.578),
      ),
      min: bezier.Point(-24.292605, 1.662),
      max: bezier.Point(9.924615, 41.654971),
    ),
    BezierBBoxFixture(
      name: "generated_linear_045",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-12.872, 39.658),
        end: bezier.Point(-11.459, 26.978),
      ),
      min: bezier.Point(-12.872, 26.978),
      max: bezier.Point(-11.459, 39.658),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_045",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-1.767, 27.296),
        control: bezier.Point(41.092, 40.329),
        end: bezier.Point(34.774, 29.908),
      ),
      min: bezier.Point(-1.767, 27.296),
      max: bezier.Point(35.585703, 34.538223),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_045",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-12.614, 4.558),
        control1: bezier.Point(36.563, -10.034),
        control2: bezier.Point(49.816, -31.443),
        end: bezier.Point(-5.978, -17.941),
      ),
      min: bezier.Point(-12.614, -22.228317),
      max: bezier.Point(30.417968, 4.558),
    ),
    BezierBBoxFixture(
      name: "generated_linear_046",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-7.639, 23.237),
        end: bezier.Point(-15.164, 26.371),
      ),
      min: bezier.Point(-15.164, 23.237),
      max: bezier.Point(-7.639, 26.371),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_046",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-2.447, 2.488),
        control: bezier.Point(32.834, 0.952),
        end: bezier.Point(-27.417, -31.516),
      ),
      min: bezier.Point(-27.417, -31.516),
      max: bezier.Point(10.582655, 2.488),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_046",
      curve: bezier.CubicBezierData(
        start: bezier.Point(8.283, -15.415),
        control1: bezier.Point(-2.277, 8.172),
        control2: bezier.Point(0.912, -0.195),
        end: bezier.Point(-5.076, -0.825),
      ),
      min: bezier.Point(-5.076, -15.415),
      max: bezier.Point(8.283, 1.123946),
    ),
    BezierBBoxFixture(
      name: "generated_linear_047",
      curve: bezier.LinearBezierData(
        start: bezier.Point(32.494, -24.363),
        end: bezier.Point(46.46, 17.469),
      ),
      min: bezier.Point(32.494, -24.363),
      max: bezier.Point(46.46, 17.469),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_047",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-33.136, 15.268),
        control: bezier.Point(-2.15, -1.331),
        end: bezier.Point(7.081, 15.37),
      ),
      min: bezier.Point(-33.136, 6.993922),
      max: bezier.Point(7.081, 15.37),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_047",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-40.789, -48.357),
        control1: bezier.Point(-13.028, -44.436),
        control2: bezier.Point(38.349, -41.03),
        end: bezier.Point(28.551, 28.292),
      ),
      min: bezier.Point(-40.789, -48.357),
      max: bezier.Point(29.775596, 28.292),
    ),
    BezierBBoxFixture(
      name: "generated_linear_048",
      curve: bezier.LinearBezierData(
        start: bezier.Point(-45.468, -46.127),
        end: bezier.Point(42.418, 24.68),
      ),
      min: bezier.Point(-45.468, -46.127),
      max: bezier.Point(42.418, 24.68),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_048",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(5.475, -46.488),
        control: bezier.Point(-28.069, -25.233),
        end: bezier.Point(-24.419, 47.094),
      ),
      min: bezier.Point(-24.777189, -46.488),
      max: bezier.Point(5.475, 47.094),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_048",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-45.614, 36.105),
        control1: bezier.Point(-2.283, -22.523),
        control2: bezier.Point(-27.899, 11.265),
        end: bezier.Point(-18.669, 37.429),
      ),
      min: bezier.Point(-45.614, 3.701444),
      max: bezier.Point(-18.669, 37.429),
    ),
    BezierBBoxFixture(
      name: "generated_linear_049",
      curve: bezier.LinearBezierData(
        start: bezier.Point(39.74, 21.109),
        end: bezier.Point(-8.034, -6.729),
      ),
      min: bezier.Point(-8.034, -6.729),
      max: bezier.Point(39.74, 21.109),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_049",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(20.637, 20.229),
        control: bezier.Point(-22.224, 28.784),
        end: bezier.Point(-22.697, -13.885),
      ),
      min: bezier.Point(-22.697, -13.885),
      max: bezier.Point(20.637, 21.657784),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_049",
      curve: bezier.CubicBezierData(
        start: bezier.Point(4.88, 31.197),
        control1: bezier.Point(-28.171, -37.237),
        control2: bezier.Point(-22.252, 38.93),
        end: bezier.Point(22.931, 25.809),
      ),
      min: bezier.Point(-16.120895, 2.257436),
      max: bezier.Point(22.931, 31.197),
    ),
    BezierBBoxFixture(
      name: "generated_linear_050",
      curve: bezier.LinearBezierData(
        start: bezier.Point(39.88, 20.328),
        end: bezier.Point(22.871, -21.145),
      ),
      min: bezier.Point(22.871, -21.145),
      max: bezier.Point(39.88, 20.328),
    ),
    BezierBBoxFixture(
      name: "generated_quadratic_050",
      curve: bezier.QuadraticBezierData(
        start: bezier.Point(-27.241, -32.639),
        control: bezier.Point(7.649, 16.747),
        end: bezier.Point(-16.027, -8.044),
      ),
      min: bezier.Point(-27.241, -32.639),
      max: bezier.Point(-6.455696, 0.241502),
    ),
    BezierBBoxFixture(
      name: "generated_cubic_050",
      curve: bezier.CubicBezierData(
        start: bezier.Point(-39.526, -45.99),
        control1: bezier.Point(3.748, 32.585),
        control2: bezier.Point(-46.89, -40.022),
        end: bezier.Point(-15.809, -37.024),
      ),
      min: bezier.Point(-39.526, -45.99),
      max: bezier.Point(-15.809, -9.319208),
    ),
  ]
}
