#!/usr/bin/env escript
%% Exercise the actual private selector with synthetic bucket inventories.
-mode(compile).
main(_) ->
    code:add_paths(filelib:wildcard("build/dev/erlang/*/ebin")),
    M='svg_path@intersections',
    F="build/dev/erlang/svg_path/_gleam_artefacts/svg_path@intersections.erl",
    {ok,M,Bin}=compile:file(F,[binary,export_all]),
    {module,M}=code:load_binary(M,F,Bin),
    A={quadratic_bezier,{point,0.0,0.0},{point,0.5,0.0},{point,1.0,0.0}},
    B={quadratic_bezier,{point,0.0,-0.5},{point,0.5,0.0},{point,1.0,0.5}},
    C={window_preserving_window,0.0,1.0,0.0,1.0},
    O={window_preserving_window,0.1,0.2,0.1,0.2},
    lists:foreach(fun({NC,NO,KC,KO})->
      Input=lists:duplicate(NC,{C,1})++lists:duplicate(NO,{O,1}),
      {ok,{Kept,DC,DO}}=select(M,A,B,Input,{500,500}),
      KC=length([ok||{W,_}<-Kept,W=:=C]),
      KO=length([ok||{W,_}<-Kept,W=:=O]),
      true=(DC=:=NC-KC),true=(DO=:=NO-KO),
      io:format("~p/~p input -> ~p/~p retained; ~p/~p discarded~n",[NC,NO,KC,KO,DC,DO])
    end,[{600,600,500,500},{200,900,200,800},{900,200,800,200},
         {0,1100,0,1000},{1100,0,1000,0},{100,900,100,900}]),
    %% A corner residual of zero wins even when its midpoint is worse.
    Corner={window_preserving_window,0.0,0.1,0.0,0.2},
    Midpoint={window_preserving_window,0.3,0.31,0.32,0.33},
    {ok,{Scored,0,1}}=select(M,A,A,
      [{Corner,1}|lists:duplicate(1000,{Midpoint,1})],{500,500}),
    true=lists:member({Corner,1},Scored),
    io:format("Best-of-five scoring preserves the better corner over a better midpoint.~n"),
    %% Both chord crossings are exact curve intersections. Their new scores
    %% tie at zero, so parameter order retains the wider window too, despite
    %% its worse corner/center residual.
    WideCrossing={window_preserving_window,0.0,0.9,0.0,0.9},
    NarrowCrossing={window_preserving_window,0.48,0.54,0.48,0.54},
    {ok,{CrossingScored,1,0}}=select(M,A,B,
      [{WideCrossing,1}|lists:duplicate(1000,{NarrowCrossing,1})],{500,500}),
    true=lists:member({WideCrossing,1},CrossingScored),
    io:format("Actual curve residual at the chord crossing contributes to ranking.~n"),
    none=M:elizabeth_decay_start(none,3,1000),
    {some,3}=M:elizabeth_decay_start(none,3,1001),
    {some,5}=M:elizabeth_decay_start(none,5,10),
    {some,3}=M:elizabeth_decay_start({some,3},5,10),
    {500,500}=M:elizabeth_generation_budget(2,none),
    lists:foreach(fun(Start)->
      {500,500}=M:elizabeth_generation_budget(Start,{some,Start}),
      {12,12}=M:elizabeth_generation_budget(12,{some,Start}),
      {12,12}=M:elizabeth_generation_budget(48,{some,Start}),
      Budgets=[element(1,M:elizabeth_generation_budget(G,{some,Start}))||G<-lists:seq(Start,48)],
      Budgets=lists:reverse(lists:sort(Budgets))
    end,[3,4,5]),
    {ok,{Late,570,570}}=select(M,A,B,
      lists:duplicate(600,{C,1})++lists:duplicate(600,{O,1}),{30,30}),
    60=length(Late),
    {ok,{Asymmetric,580,560}}=select(M,A,B,
      lists:duplicate(600,{C,1})++lists:duplicate(600,{O,1}),{20,40}),
    20=length([ok||{W,_}<-Asymmetric,W=:=C]),
    {ok,{Borrowed,0,950}}=select(M,A,B,
      lists:duplicate(10,{C,1})++lists:duplicate(1000,{O,1}),{30,30}),
    60=length(Borrowed),
    io:format("Generation boundaries, asymmetric reserves and late-budget lending passed.~n"),
    Empty={elizabeth_evaluation_cache,#{},0,0,#{},#{}},
    {ok,{Sample,Cache1}}=M:elizabeth_cached_pair(A,B,0.0,0.0,Empty),
    {ok,{Sample,Cache2}}=M:elizabeth_cached_pair(A,B,-0.0,0.0,Cache1),
    1=maps:size(element(2,Cache2)),2=element(3,Cache2),1=element(4,Cache2),
    {ok,{_,Cache3}}=M:elizabeth_cached_pair(A,B,1.0e-15,0.0,Cache2),
    2=maps:size(element(2,Cache3)),
    {ok,{Cross,Score,Cache4,Best}}=M:elizabeth_window_score(A,B,WideCrossing,Empty),
    6=element(3,Cache4),
    {ok,{false,_,NonCrossCache,_}}=M:elizabeth_window_score(A,A,Midpoint,Empty),
    5=element(3,NonCrossCache),
    {ok,{Cross,Score,Cache5,Best}}=M:elizabeth_window_score(A,B,WideCrossing,Cache4),
    true=element(2,Cache4)=:=element(2,Cache5),
    true=element(4,Cache5)>element(4,Cache4),
    Curved={quadratic_bezier,{point,0.0,0.0},{point,0.1,0.8},{point,1.0,0.0}},
    lists:foldl(fun(W,Cache)->
      {ok,{X,Y,Next,_}}=M:elizabeth_window_score(Curved,B,W,Cache),
      {X,Y}=reference_score(M,Curved,B,W),Next
    end,Empty,[C,WideCrossing,NarrowCrossing,C]),
    io:format("Exact pair caching, signed zero, distinct nearby keys and repeated score checks passed.~n"),
    Location=fun({_,P})->P end,
    Items=[{a,{0.0,0.0}},{b,{0.01,0.01}},{c,{0.9,0.9}}],
    [{a,_},{c,_}]=M:select_spatially_diverse(Items,Location,2,0.0),
    [{a,_},{c,_},{b,_}]=M:select_spatially_diverse(Items,Location,3,0.0),
    Identical=[{a,{0.0,0.0}},{b,{0.0,0.0}},{c,{0.0,0.0}}],
    Identical=M:select_spatially_diverse(Identical,Location,9,0.0),
    [{a,_}]=M:select_spatially_diverse(Identical,Location,9,1.0e-7),
    []=M:select_spatially_diverse(Items,Location,0,0.0),
    Edge=[{a,{0.0,0.0}},{b,{1.0e-7,0.0}},{c,{0.5e-7,0.0}}],
    [{a,_},{b,_}]=M:select_spatially_diverse(Edge,Location,9,1.0e-7),
    io:format("Shared diversity selector: coverage, zero-floor fill, occurrence identity and positive floor passed.~n"),
    %% Synthetic candidates exercise selection order, not root validity.
    Pool=[{segment_intersection,T,T,{point,0.0,0.0}}||T<-[0.5,0.5000002,0.5000004,0.5000006,0.5000008,0.9]],
    {ok,Selected}=M:elizabeth_select_candidates(A,B,Pool),
    4=length(Selected),
    true=lists:any(fun({segment_intersection,T,_,_})->T=:=0.9 end,Selected),
    true=lists:any(fun({segment_intersection,T,_,_})->T=:=0.5 end,Selected),
    {ok,Selected}=M:elizabeth_select_candidates(A,B,lists:reverse(Pool)),
    io:format("Coarse-first selection retains worse-residual distant candidate; deterministic under reversed input.~n").
select(M,A,B,Windows,Budget)->
    {ok,{Kept,DC,DO,_}}=M:elizabeth_beam_select(A,B,Windows,Budget,{elizabeth_evaluation_cache,#{},0,0,#{},#{}}),
    {ok,{Kept,DC,DO}}.
reference_score(M,A,B,{window_preserving_window,U,V,W,Z})->
    {ok,P}=svg_path:segment_point(A,U),{ok,Q}=svg_path:segment_point(A,V),
    {ok,R}=svg_path:segment_point(B,W),{ok,S}=svg_path:segment_point(B,Z),
    Cross=M:window_preserving_chord_crossing(P,Q,R,S),
    Pairs=[{U,W},{U,Z},{V,W},{V,Z},{(U+V)/2,(W+Z)/2}],
    Extra=case Cross of none->[];{some,{T1,T2}}->[{U+T1*(V-U),W+T2*(Z-W)}] end,
    Scores=[begin {ok,X}=svg_path:segment_point(A,T),{ok,Y}=svg_path:segment_point(B,H),M:window_preserving_point_distance(X,Y) end||{T,H}<-Pairs++Extra],
    {Cross=/=none,lists:min(Scores)}.
